---
- hosts: barry.local
  become: pi
  vars:
    backup_dir: ~/local-rpi-server/backup-config
  tasks:
  - name: backup pre-wifi config files
    copy: src={{ item }} dest={{ backup_dir }}/{{ item | basename }}  
    with_items:
      - /etc/hostapd/hostapd.conf
      - /etc/default/hostapd
      - /etc/sysctl.conf
      - /etc/dnsmasq.conf
      - /etc/network/interfaces
      - /etc/dhcpcd.conf
      - /etc/cups/cupsd.conf
