---
- hosts: all
  # run this: ansible-playbook -i raspberrypi.local, -u pi configure-rpi.yaml -e new_hostname=barrybig -e domain="snb-home"

  tasks:

    # for home assistant
  - name: change password
    user:
      name: pi
      password: $6$/5ndW1SIsXFJCHZ6$xa1uq6z3EJTvAWxvWTijTx.QIF8kjljdZVycFDpj7y5sw5zvRigUM74rsyGyx088r9Ib9lB.4R8p/xmuWrcZP0
      update_password: always
    become: yes

  - name: stop bluetooth stuff
    systemd: name={{ item }} state=stopped enabled=no
    become: yes
    with_items:
      - hciuart
      - bluetooth

  - name: upgrade system
    become: yes
    apt:
      # upgrade: dist
      upgrade: full
  
  - name: remove unnecessary packages
    become: yes
    apt:
      name: "{{ item }}"
      state: absent
      autoremove: yes
    with_items:
      - wolfram-engine
      - sonic-pi
      - bluej
      - greenfoot

  - name: install necessary packages
    apt: pkg={{ item }} update_cache=yes cache_valid_time=86400
    become: yes
    with_items:
      - git
      - emacs25
      - vim-nox

  - name: run stuff
    command: {{ item }}
    become: yes
    with_items:
      - "timedatectl set-timezone {{ timezone }}"

  - name: get spacemacs
    git:
      # repo: ssh://git@github.com:oneyb/config.git
      repo: https://github.com/syl20bnr/spacemacs 
      dest: "{{ ansible_user_home }}/.emacs.d/"
      update: yes

  - name: install spacemacs packages
    command: "emacs --daemon | yes"

  # - name: get config
  #   git:
  #     # repo: ssh://git@github.com:oneyb/config.git
  #     repo: https://github.com/oneyb/config.git
  #     dest: documents/config
  #     update: yes

  # - name: install config
  #   command: bash documents/config/.copy-config.sh in

  - name: make ~/bin
    file:
      path: "{{ ansible_env.HOME }}/bin"
      state: directory

    
  # - name: install vim-plug NOW managed from VIM
  #   get_url:
  #     url: https://raw.githubusercontent.com/platformio/platformio-core/develop/scripts/99-platformio-udev.rules
  #     dest: "{{ ansible_env.HOME }}/.vim/autoload/plug.vim"
  # - name: install vim plug-ins
  #   command: vim +PlugInstall +qall

  - name: add basic command line control
    lineinfile: dest="{{ item.dest }}" line="{{ item.line }}"
    with_items:
      - { dest: "{{ ansible_env.HOME }}/.bashrc", line: "set -o vi" }
      - { dest: "{{ ansible_env.HOME }}/.bashrc", line: "alias ll='ls -al'" }


  # - name: set uart according to 'https://hallard.me/enable-serial-port-on-raspberry-pi/'
  # - replace:
  #     path: /boot/config.txt
  #     regexp: 'enable_uart=0'
  #     replace: 'enable_uart=1' 
  #     become: yes
  #     # backup: yes
  # # SEE BELOW

  # - name: set raspberry options
  #   command: {{ item | quote }}
  #   become: yes
  #   with_items:
  #     # - raspi-config nonint do_expand_rootfs
  #     # - raspi-config nonint do_hostname {{ hostname }}
  #     # - raspi-config nonint do_boot_behaviour B1
  #     # - raspi-config nonint do_boot_behaviour B2
  #     # - raspi-config nonint do_boot_behaviour B3
  #     # - raspi-config nonint do_boot_behaviour B4
  #     # - raspi-config nonint do_boot_wait 1
  #     # - raspi-config nonint do_boot_splash 1
  #     # - raspi-config nonint do_overscan 1
  #     # - raspi-config nonint do_camera 1
  #     # - raspi-config nonint do_ssh 1
  #     # - raspi-config nonint do_vnc 1
  #     # - raspi-config nonint do_spi 1
  #     # - raspi-config nonint do_i2c 1
  #     - raspi-config nonint do_serial 1
  #     # - raspi-config nonint do_onewire 1
  #     # - raspi-config nonint do_rgpio 1
  #     # - raspi-config nonint do_overclock %s
  #     # - raspi-config nonint do_memory_split 1
  #     # - raspi-config nonint do_resolution %d %d
  #     # - raspi-config nonint do_wifi_country %s

  # - name: set serial to on
  #   command: raspi-config nonint dtoverlay=pi3-disable-bt
  #   become: yes


  - name: change hostname to own
    become: yes
    replace:
      path: /etc/hosts
      after: '127\.0\..*$'
      regexp: '127\.0\..*$'
      replace: '127.0.1.1\t{{ domain }} {{ new_hostname }}'

  - name: rebooting things
    shell: systemctl reboot
    become: yes
    async: 0
    poll: 0

  - name: wait for rebooted computer to test for changes
    local_action: wait_for host="{{ new_hostname }}.local" state=started
