---
- hosts: all
  vars:
    backup_dir: "{{ playbook_dir }}/backup-preinstall"
    template_dir: "{{ playbook_dir }}/templates"
  tasks:
  - name: get secrets
    include_vars: file=secrets.yaml
    # include_vars: file=config.yaml
  - name: install necessary packages
    apt: 
      update_cache: yes
      cache_valid_time: 86400
      name: "{{ packages }}"
    vars:
      packages:
        - hostapd
        - dnsmasq
        - udhcpd
        - libtool
        - libtool-bin
        - python3-pip
        - libsnmp-dev
        - snmp
  # - name: restore wifi config files
  #   copy: src={{ backup_dir }}/{{ item | basename }} dest={{ item }} owner=root mode=0600
  #   become: yes
  #   become_method: sudo
  #   with_items:
  #     - /etc/hostapd/hostapd.conf
  #     - /etc/default/hostapd
  #     - /etc/sysctl.conf
  #     - /etc/dnsmasq.conf
  #     - /etc/network/interfaces
  #     - /etc/dhcpcd.conf
  #     - /etc/default/udhcpd
  #     - /etc/iptables.ipv4.nat
  #     - /etc/cups/cupsd.conf
  - name: fill and copy wifi config files
    template: 
      src: '{{ template_dir }}/{{ item | basename }}' 
      dest: '{{ item }}' 
      owner: root 
      mode: 0600
      backup: yes
    become: yes
    with_items:
      - /etc/hostapd/hostapd.conf
      - /etc/default/hostapd
      - /etc/sysctl.conf
      - /etc/dnsmasq.conf
      - /etc/network/interfaces
      - /etc/udhcpd.conf
      # - /etc/default/udhcpd
      - /etc/iptables.ipv4.nat
  - name: (re)start necessary services
    systemd: name={{ item }} state=restarted daemon_reload=yes enabled=yes no_block=yes
    become: yes
    with_items:
      - udhcpd
      - hostapd
      - dnsmasq
      - avahi-daemon
      - networking
    ignore_errors: true
    

  - name: waiting for server to come back after services
    wait_for_connection:

  - name: disable necessary/blocking services
    systemd: name={{ item }} state=stopped enabled=no
    become: yes
    ignore_errors: yes
    with_items:
      # - NetworkManager
      - dhcpcd

  - name: restart server
    shell: sleep 2 && systemctl reboot
    async: 1
    poll: 0
    become: yes
    ignore_errors: true

  - name: waiting for server to come back after services
    wait_for_connection:

  # - name: disable necessary/blocking services with error handling
  #   block:
  #     - debug:
  #       msg: 'I execute normally'
  #     - systemd: name={{ item }} state=stopped enabled=no
  #       become: yes
  #       ignore_errors: yes
  #       with_items:
  #         - NetworkManager
  #   rescue:
  #     - debug:
  #       msg: 'I caught an error'

